### PR TITLE
Added data

### PR DESCRIPTION
**Pull request by COil**

### CODE REVIEW

**Comment by lennerd** [comment]
🙇  nice PR. Where do you get all the infos from?

**Comment by COil** [comment]
hi, from our user meta logs, and then I search on the web if I can find related infos.

**Comment by lennerd** [comment]
Nice. Let's merge it. We have problems with the composer.json file due to #43. A fix and a new patch version is on it's way.

**Comment by lennerd** [comment]
Oh sorry, didn't intend to close it.

**Pull request merged**
