### PR TITLE
Fixing error with Google Bot detection

### PR DESCRIPTION
**Pull request by smilesrg**
Fixed error with detection any user-agent as google bot

### CODE REVIEW

**Comment by smilesrg** [comment]
@lennerd please accept

**Comment by lennerd** [comment]
What exactly is the problem here?

**Comment by lennerd** [comment]
Ah, now I see, that you made two PRs. Would you mind to combine them into one?

**Comment by smilesrg** [comment]
@lennerd I tried, but I couldn't, I've just made quick edit via web interface.

**Comment by smilesrg** [comment]
@lennerd this PR is bugfix. Because all user-agents with empty string would be detected as google bot.

**Comment by smilesrg** [comment]
Even ```Mozilla/5.0 TargetsHelperTest``` is detected as Google Bot! Please accept this PR

**Comment by lennerd** [comment]
Believe it or not but I'm working beside administrating this example. :wink: 

I will look into this bug as soon as possible. At the mean time please have a look on how to [clone a git repository](https://help.github.com/articles/fetching-a-remote/) and [how to submit PRs](https://help.github.com/articles/using-pull-requests/), so that you can combine both PRs into one greater bugfix. :wink:

**Comment by lennerd** [comment]
Did you manage to setup the Repository on your local machine?

**Comment by smilesrg** [comment]
@lennerd yes, I did.

**Comment by lennerd** [comment]
Great, can you than push your changes to your forked repo and create a new PR again?

**Comment by lennerd** [comment]
Forget, what I wrote. I will look into your PR and merge it as soon as possible. Thank you again.

**Pull request closed without merging**
