### PR TITLE
Added several bots for Twitter

### PR DESCRIPTION
**Pull request by smilesrg**

### CODE REVIEW

**Comment by smilesrg** [comment]
@lennerd I will be very grateful, if you update the library with this PR :-)

**Comment by lennerd** [comment]
Thank you for your PR. 👍

Just a comment for the Twitter bots. Posting links to Twitter means Twitter crawls the linked webpage, doesn't it? Sounds like a crawler.

**Comment by smilesrg** [comment]
Yes, I thought about that too! :-) But we have Twitterbot that crawls links too. So I decided to put it together. But if you think it's better to move new bots/crawers to crawlers section - okay, I'll do it, just tell me your final thoughts.

**Comment by lennerd** [comment]
Yes please move them over to extened crawlers, so I can merge this.

**Comment by smilesrg** [comment]
@lennerd done!

**Comment by lennerd** [comment]
Thank you! :+1:

**Comment by smilesrg** [comment]
@lennerd Can you please do something that I can update library to the latest version via composer?

**Comment by smilesrg** [comment]
I have vipx/bot-detect-bundle installed on my Symfony2 project. But ``` composer update vipx/bot-detect``` says ```Nothing to install or update```

**Comment by lennerd** [comment]
I added release v1.1.5. You should be able to update now.

If you want to upgrade the package to the newest development version, you can always use the `dev-master` as the required version.

**Comment by smilesrg** [comment]
```
[vagrant@localhost trim]$ php composer.phar require vipx/bot-detect:1.1.5
./composer.json has been updated
Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package vipx/bot-detect could not be found in any version, there may be a typo in the package name.
  Problem 2
    - vipx/bot-detect-bundle v2.0.1 requires vipx/bot-detect ~1.0 -> no matching package found.
    - vipx/bot-detect-bundle v2.0.1 requires vipx/bot-detect ~1.0 -> no matching package found.
    - vipx/bot-detect-bundle v2.0.1 requires vipx/bot-detect ~1.0 -> no matching package found.
    - Installation request for vipx/bot-detect-bundle == 2.0.1.0 -> satisfiable by vipx/bot-detect-bundle[v2.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by smilesrg** [comment]
However, dev-master seems to be working!

```
[vagrant@localhost trim]$ php composer.phar require vipx/bot-detect:dev-master
./composer.json has been updated
Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
  - Removing vipx/bot-detect (v1.1.4)
  - Installing vipx/bot-detect (dev-master fabded8)
    Cloning fabded88bf63a6fe9ceb913eef49c6d89a1049c3
```

**Comment by lennerd** [comment]
Looks like you have issues in your connection to packagist.org. Did you try to fix those?

**Comment by lennerd** [comment]
````
$ composer update vipx/bot-detect   
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating vipx/bot-detect (v1.0.3 => v1.1.5)
    Checking out fabded88bf63a6fe9ceb913eef49c6d89a1049c3

Writing lock file
Generating autoload files

**Comment by smilesrg** [comment]
Yes, connection troubles has disappeared, everything works as expected if upgrading to ```dev-master``` version.

**Comment by smilesrg** [comment]
Thank you!

**Pull request merged**
