### PR TITLE
Pull request to fix fatal error

### PR DESCRIPTION
**Pull request by h3rj4n**
See issue #37 for more details.

### CODE REVIEW

**Comment by lennerd** [comment]
When reviewing your PR, I realized that we do not test against older version of Symfony. The ConfigCache class does not have a `__toString` method any more since version 3.0. But this library should also work with Symfony 2.3.

I will fix the travis configuration. Do you think you can extend your PR to also work with Symfony 2.3 and up?

**Comment by lennerd** [comment]
Via #39 I added Travis configuration for Symfony 3. Please rebase your PR branch now.

**Comment by lennerd** [comment]
For information on rebasing your PR: http://juanitofatas.com/2015/02/22/rebase-pull-request/

**Comment by lennerd** [comment]
This is a quite critical bug. Do you have time for updating this PR? Otherwise I would make an own PR based on your changes.

**Comment by h3rj4n** [comment]
I won't be able to change anything until this evening (EU time). I'll update the PR if you haven't fixed it already.

**Comment by lennerd** [comment]
Sounds good to me. If you have any problems with rebasing, don't hesitate to ask.

**Pull request closed without merging**
